lab1 trying to add hw Razumova
OSLL/os-hse-1h2019 pull request #26
Opened 2019-04-23 08:39 UTC by Shasha33

2019-05-02 21:44 UTC, Shasha33 commented
Отправила diff именно этого кода
https://stepik.org/submissions/218134/105902635?unit=32918

2019-05-10 12:36 UTC, krinkin commented on solutions/raz/lab1/kern/monitor.c
> +	test();
Don't understand this. Could you elaborate?

2019-05-10 12:38 UTC, krinkin commented on solutions/raz/lab1/kern/monitor.c
> +	return *((int*) k);
could you explain the purpose of this?

2019-05-10 12:38 UTC, krinkin requested changes
PLease answer questions inlined

2019-05-10 12:55 UTC, Shasha33 commented on solutions/raz/lab1/kern/monitor.c
> +	return *((int*) k);
Эта функция разыменовывает указатель, который представлен в виде инта, и возвращает значение

2019-05-10 12:57 UTC, Shasha33 commented on solutions/raz/lab1/kern/monitor.c
> +	test();
Сначала это была функция, в которую перенесена часть кода, но в концу работы в ней оказалось все необходимое и код из mon_backtrace пропал

2019-05-10 12:59 UTC, Shasha33 commented on solutions/raz/lab1/kern/monitor.c
> +	test();
Подумала, что можно это не убирать, если вид кода не будет оцениваться

2019-05-10 15:15 UTC, krinkin approved these changes

2019-05-10 15:15 UTC, merged