add lab2 kra
OSLL/os-hse-1h2019 pull request #33
Opened 2019-05-02 21:55 UTC by anstkras

2019-05-02 21:55 UTC, anstkras commented
https://stepik.org/submissions/218135/105894333?unit=32920

2019-05-10 15:32 UTC, krinkin requested changes

2019-05-10 15:32 UTC, krinkin commented on solutions/kra/lab2/kern/pmap.c
> +	if((uint32_t)nextfree - KERNBASE >= 0xfffffff) {
Please explain this magic number

2019-05-10 15:42 UTC, anstkras commented on solutions/kra/lab2/kern/pmap.c
> +	if((uint32_t)nextfree - KERNBASE >= 0xfffffff) {
4 Gb

2019-05-10 15:49 UTC, krinkin commented on solutions/kra/lab2/kern/pmap.c
> +	if((uint32_t)nextfree - KERNBASE >= 0xfffffff) {
4Gb=0xffffffff

2019-05-10 16:03 UTC, anstkras commented on solutions/kra/lab2/kern/pmap.c
> +	if((uint32_t)nextfree - KERNBASE >= 0xfffffff) {
Точно, исправлено

2019-05-17 18:23 UTC, krinkin approved these changes

2019-05-17 18:24 UTC, merged