lab2 done
OSLL/os-hse-1h2019 pull request #38
Opened 2019-05-09 20:33 UTC by zuevmaxim

https://stepik.org/submissions/218135/107192730?unit=32920

2019-05-10 15:41 UTC, krinkin requested changes

2019-05-10 15:41 UTC, krinkin commented on solutions/zue/lab2/kern/pmap.c
> +	boot_map_region(kern_pgdir, KERNBASE, 0xffffffff - KERNBASE, 0, PTE_W | PTE_P);
Could you explain this magic number?

2019-05-11 14:02 UTC, zuevmaxim commented on solutions/zue/lab2/kern/pmap.c
> +	boot_map_region(kern_pgdir, KERNBASE, 0xffffffff - KERNBASE, 0, PTE_W | PTE_P);
Должно быть: size = 2^32 - KERNBASE = 0xffffffff - KERNBASE + 1 -- я забыл единичку

2019-05-17 18:24 UTC, krinkin approved these changes

2019-05-17 18:24 UTC, merged