lab2 raz
OSLL/os-hse-1h2019 pull request #46
Opened 2019-05-12 11:58 UTC by Shasha33

https://stepik.org/submissions/218135/107629877?unit=32920

2019-05-17 19:02 UTC, krinkin requested changes

2019-05-17 19:02 UTC, krinkin commented on solutions/raz/lab2/kern/pmap.c
> +	boot_map_region(kern_pgdir, KERNBASE, (1LL << 32) - KERNBASE, 0, PTE_W);
Could you explain this?

2019-05-17 20:27 UTC, Shasha33 commented on solutions/raz/lab2/kern/pmap.c
> +	boot_map_region(kern_pgdir, KERNBASE, (1LL << 32) - KERNBASE, 0, PTE_W);
Как и написано в задании выше, мы отображаем отрезок виртуальной памяти, начиная с KERNBASE размером 2^32 - KERNBASE на отрезок физической памяти, начиная с 0, с разрешением писать.

2019-06-03 13:07 UTC, krinkin commented on solutions/raz/lab2/kern/pmap.c
> +	boot_map_region(kern_pgdir, KERNBASE, (1LL << 32) - KERNBASE, 0, PTE_W);
It worth to avoid any magic number in your code in the future

2019-06-03 13:07 UTC, merged