lab2 done
OSLL/os-hse-1h2019 pull request #49
Opened 2019-05-12 20:45 UTC by mixNIK999

2019-06-03 14:37 UTC, krinkin requested changes

2019-06-03 14:37 UTC, krinkin commented on solutions/nik/lab2/kern/pmap.c
> +        boot_map_region(kern_pgdir, KERNBASE, (1LL << 32) - KERNBASE, 0, PTE_W);
Magic numbers? What is it?

2019-06-05 07:41 UTC, merged

2019-06-06 16:15 UTC, mixNIK999 commented on solutions/nik/lab2/kern/pmap.c
> +        boot_map_region(kern_pgdir, KERNBASE, (1LL << 32) - KERNBASE, 0, PTE_W);
(1LL << 32) -- верхняя граница памяти (всего используем 4GB), т.е. последний адрес на который мы можем ссылаться = (1LL << 32) - 1 = 0xffffffff. По хорошему, конечно, нужно завести константу (нужно ли закормить это?).
Чтобы не переполниться используем 64 битный long long.

2019-06-07 04:42 UTC, krinkin commented on solutions/nik/lab2/kern/pmap.c
> +        boot_map_region(kern_pgdir, KERNBASE, (1LL << 32) - KERNBASE, 0, PTE_W);
- Для всех адресов есть константы, надо разобраться и использовать их
- почитайте внимательно файл memlayout.h

2019-06-07 13:28 UTC, mixNIK999 commented on solutions/nik/lab2/kern/pmap.c
> +        boot_map_region(kern_pgdir, KERNBASE, (1LL << 32) - KERNBASE, 0, PTE_W);
Действительно, можно не вводить дополнительные константы, а заметить что унарный минус от для беззнакового 32 битного числа - это расстояние до 2^32. Таким образом можно заменить (1LL << 32) - KERNBASE, на - KERNBASE и не использовать магические числа или новые константы.